os: osx

sudo: false

addons:
  homebrew:
    taps: henkrehorst/php
    packages:
      - composer
      - valet-php@7.2
    update: true

before_cache:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/Library/Caches/Homebrew
