language: php

os: osx

sudo: false

before_install:
  - travis_retry composer self-update

install:
  - composer install

cache:
  directories:
    - $HOME/.composer/cache

script:
- echo "skipping tests"