os: osx

sudo: false

addons:
  homebrew:
    taps: henkrehorst/php
    packages:
      - composer
      - valet-php@7.2
    update: true

before_cache:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then find /usr/local/Homebrew \! -regex ".+\.git.+" -delete; fi

cache:
  directories:
    - $HOME/.composer/cache
    # Homebrew cache to improve performance.
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Homebrew
