language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  global:
    - setup=basic
    - APP_ENV=testing

sudo: false

before_install:
  - travis_retry composer self-update

cache:
  directories:
    - $HOME/.composer/cache
