language: php

os: osx

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

sudo: false

before_install:
  - travis_retry composer self-update

install:
  - composer install

cache:
  directories:
    - $HOME/.composer/cache

script:
- echo "skipping tests"