trigger:
- master
- 2.x

# Build on Mojave and High Sierra
strategy:
  matrix:
    mojave:
      imageName: 'macOS-10.14'
      mariadb: false
    highsierra:
      imageName: 'macOS-10.13'
      mariadb: false
    mojave-mariadb:
      imageName: 'macOS-10.14'
      mariadb: true
    highsierra-mariadb:
      imageName: 'macOS-10.13'
      mariadb: true

pool:
  vmImage: $(imageName)

steps:

# Valet install command test cases

- script: |
    brew tap henkrehorst/php
    brew install valet-php@7.2
  displayName: '[INSTALL] valet-php@7.2'

- script: |
    brew install composer
    composer install
  displayName: '[INSTALL] composer'

# If the code style does not pass there is no need to run other tests.
- script: |
    ./vendor/squizlabs/php_codesniffer/bin/phpcs
  displayName: '[CODE STYLE] Check PSR-2'

- script: |
    ./valet fix
    ./valet install --with-mariadb
  displayName: '[INSTALL] valet-plus with MariaDB'
  condition: eq(variables['mariadb'], true)

- script: |
    ./valet fix
    ./valet install
  displayName: '[INSTALL] valet-plus'
  condition: eq(variables['mariadb'], false)

# Test MySQL Commands

- script: |
    mysql --help | grep -A1 "Default options are read"
  displayName: '[MYSQL] print available config paths '

- script: |
    ./valet db pwd root
  displayName: '[MYSQL] set the mysql root user password'

- script: |
    ./valet db ls
  displayName: '[MYSQL] database list command'
