trigger:
- release/azure-pipelines

strategy:
  matrix:
    mojave:
      imageName: 'macOS-10.14'
    highsierra:
      imageName: 'macOS-10.13'

pool:
  vmImage: $(imageName)

steps:

# Valet install command test cases

- script: |
    brew tap henkrehorst/php
    brew install valet-php@7.2
  displayName: '[INSTALL] Install valet-php@7.2'

- script: |
    brew install composer
    composer install
  displayName: '[INSTALL] Install composer'

- script: |
    export PATH="$PATH:`pwd`/bin"
    ./valet fix
    ./valet install
  displayName: '[INSTALL] Install valet-plus'

# PHP 5.6 Command test cases

- script: |
    export PATH="$PATH:`pwd`/bin"
    ./valet use 5.6
    php -v
  displayName: '[PHP 5.6] Switch to'

- script: |
    export PATH="$PATH:`pwd`/bin"
    ./valet xdebug on
    ./valet xdebug off
  displayName: '[PHP 5.6] xdebug on and off'

- script: |
    export PATH="$PATH:`pwd`/bin"
    ./valet ioncube on
    ./valet ioncube off
  displayName: '[PHP 5.6] ioncube on and off'

# PHP 7.0 Command test cases

- script: |
    export PATH="$PATH:`pwd`/bin"
    ./valet use 7.0
    php -v
  displayName: '[PHP 7.0] Switch to'

- script: |
    export PATH="$PATH:`pwd`/bin"
    ./valet xdebug on
    ./valet xdebug off
  displayName: '[PHP 7.0] xdebug on and off'

- script: |
    export PATH="$PATH:`pwd`/bin"
    ./valet ioncube on
    ./valet ioncube off
  displayName: '[PHP 7.0] ioncube on and off'

# PHP 7.1 Command test cases

- script: |
    export PATH="$PATH:`pwd`/bin"
    ./valet use 7.1
    php -v
  displayName: '[PHP 7.1] Switch to'

- script: |
    export PATH="$PATH:`pwd`/bin"
    ./valet xdebug on
    ./valet xdebug off
  displayName: '[PHP 7.1] xdebug on and off'

- script: |
    export PATH="$PATH:`pwd`/bin"
    ./valet ioncube on
    ./valet ioncube off
  displayName: '[PHP 7.1] ioncube on and off'

# PHP 7.2 Command test cases

- script: |
    export PATH="$PATH:`pwd`/bin"
    ./valet use 7.2
    php -v
  displayName: '[PHP 7.2] Switch to'

- script: |
    export PATH="$PATH:`pwd`/bin"
    ./valet xdebug on
    ./valet xdebug off
  displayName: '[PHP 7.2] xdebug on and off'

- script: |
    export PATH="$PATH:`pwd`/bin"
    ./valet ioncube on
    ./valet ioncube off
  displayName: '[PHP 7.2] ioncube on and off'

# PHP 7.3 Command test cases

- script: |
    export PATH="$PATH:`pwd`/bin"
    ./valet use 7.3
    php -v
  displayName: '[PHP 7.3] Switch to'

- script: |
    export PATH="$PATH:`pwd`/bin"
    ./valet xdebug on
    ./valet xdebug off
  displayName: '[PHP 7.3] xdebug on and off'

- script: |
    export PATH="$PATH:`pwd`/bin"
    ./valet ioncube on
    ./valet ioncube off
  displayName: '[PHP 7.3] ioncube on and off'

# Test Memcached

- script: |
    export PATH="$PATH:`pwd`/bin"
    ./valet memcache install
    ./valet memcache uninstall
  displayName: '[Memcached] install and uninstall'