trigger:
- release/azure-pipelines
- master
- 2.x

# Trigger on every PR towards 2.x or master
pr:
- master
- 2.x

# Build on Mojave and High Sierra
strategy:
  matrix:
    mojave:
      imageName: 'macOS-10.14'
    highsierra:
      imageName: 'macOS-10.13'

pool:
  vmImage: $(imageName)

steps:

# Valet install command test cases

- script: |
    brew tap henkrehorst/php
    brew install valet-php@7.2
  displayName: '[INSTALL] valet-php@7.2'

- script: |
    brew install composer
    composer install
  displayName: '[INSTALL] composer'

- script: |
    ./valet fix
    ./valet install
  displayName: '[INSTALL] valet-plus'

## PHP 5.6 Command test cases
#
#- script: |
#    export PATH="$PATH:`pwd`/bin"
#    ./valet use 5.6
#    php -v
#  displayName: '[PHP 5.6] Switch to'
#
#- script: |
#    ./valet xdebug on
#    ./valet xdebug off
#  displayName: '[PHP 5.6] xdebug on and off'
#
#- script: |
#    ./valet ioncube on
#    ./valet ioncube off
#  displayName: '[PHP 5.6] ioncube on and off'
#
## PHP 7.0 Command test cases
#
#- script: |
#    ./valet use 7.0
#    php -v
#  displayName: '[PHP 7.0] Switch to'
#
#- script: |
#    ./valet xdebug on
#    ./valet xdebug off
#  displayName: '[PHP 7.0] xdebug on and off'
#
#- script: |
#    ./valet ioncube on
#    ./valet ioncube off
#  displayName: '[PHP 7.0] ioncube on and off'
#
## PHP 7.1 Command test cases
#
#- script: |
#    ./valet use 7.1
#    php -v
#  displayName: '[PHP 7.1] Switch to'
#
#- script: |
#    ./valet xdebug on
#    ./valet xdebug off
#  displayName: '[PHP 7.1] xdebug on and off'
#
#- script: |
#    ./valet ioncube on
#    ./valet ioncube off
#  displayName: '[PHP 7.1] ioncube on and off'
#
## PHP 7.2 Command test cases
#
#- script: |
#    ./valet use 7.2
#    php -v
#  displayName: '[PHP 7.2] Switch to'
#
#- script: |
#    ./valet xdebug on
#    ./valet xdebug off
#  displayName: '[PHP 7.2] xdebug on and off'
#
#- script: |
#    ./valet ioncube on
#    ./valet ioncube off
#  displayName: '[PHP 7.2] ioncube on and off'
#
## PHP 7.3 Command test cases
#
#- script: |
#    ./valet use 7.3
#    php -v
#  displayName: '[PHP 7.3] Switch to'
#
#- script: |
#    ./valet xdebug on
#    ./valet xdebug off
#  displayName: '[PHP 7.3] xdebug on and off'
#
#- script: |
#    ./valet ioncube on
#    ./valet ioncube off
#  displayName: '[PHP 7.3] ioncube on and off'

# Test Memcached

- script: |
    brew reinstall pkg-config
    ./valet memcache install
  displayName: '[MEMCACHED] install'

- script: |
    ./valet memcache uninstall
  displayName: '[MEMCACHED] uninstall'