trigger:
- release/azure-pipelines

pool:
  vmImage: 'macOS-10.14'

steps:

- script: |
    brew update
    brew tap henkrehorst/php
    brew install valet-php@7.2
    brew install composer
  displayName: 'Install valet-php@7.2 dependency'

- script: |
    composer global config repositories.repo-name vcs https://github.com/Neodork/valet-plus
    composer global require neodork/repo:dev-release-azure-pipelines
    export PATH="$PATH:$HOME/.composer/vendor/bin"
    valet fix
    valet install
  displayName: 'Install valet-plus'