trigger:
- release/azure-pipelines

strategy:
  matrix:
    mojave:
      imageName: 'macOS-10.14'
    highsierra:
      imageName: 'macOS-10.13'

pool:
  vmImage: $(imageName)

steps:

- script: |
    cd bin
    ln -s ../valet valet
    cd ..
  displayName: 'Prepare binary folder'

- script: |
    brew tap henkrehorst/php
    brew install valet-php@7.2
  displayName: 'Install valet-php@7.2'

- script: |
    brew install composer
    composer install
  displayName: 'Install composer'

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet fix
    valet install
  displayName: 'Install valet-plus'

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet use 5.6
  displayName: 'Test switching to PHP 5.6'

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet use 7.0
  displayName: 'Test switching to PHP 7.0'

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet use 7.1
  displayName: 'Test switching to PHP 7.1'

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet use 7.2
  displayName: 'Test switching to PHP 7.2'

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet use 7.3
  displayName: 'Test switching to PHP 7.3'