trigger:
- release/azure-pipelines

strategy:
  matrix:
    mojave:
      imageName: 'macOS-10.14'
    highsierra:
      imageName: 'macOS-10.13'

pool:
  vmImage: $(imageName)

steps:

# Valet install command test cases

- script: |
    cd bin
    ln -s ../valet valet
    cd ..
  displayName: 'Prepare binary folder'

- script: |
    brew tap henkrehorst/php
    brew install valet-php@7.2
  displayName: 'Install valet-php@7.2'

- script: |
    brew install composer
    composer install
  displayName: 'Install composer'

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet fix
    valet install
  displayName: 'Install valet-plus'

# PHP 5.6 Command test cases

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet use 5.6
  displayName: 'Test switching to PHP 5.6'

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet xdebug on
    valet xdebug off
  displayName: 'PHP 5.6 xdebug on and off'

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet ioncube on
    valet ioncube off
  displayName: 'PHP 5.6 ioncube on and off'

# PHP 7.0 Command test cases

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet use 7.0
  displayName: 'Test switching to PHP 7.0'

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet xdebug on
    valet xdebug off
  displayName: 'PHP 7.0 xdebug on and off'

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet ioncube on
    valet ioncube off
  displayName: 'PHP 7.0 ioncube on and off'

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet memcache on
    valet memcache off
  displayName: 'PHP 7.0 memcached on and off'

# PHP 7.1 Command test cases

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet use 7.1
  displayName: 'Test switching to PHP 7.1'

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet xdebug on
    valet xdebug off
  displayName: 'PHP 7.1 xdebug on and off'

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet ioncube on
    valet ioncube off
  displayName: 'PHP 7.1 ioncube on and off'

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet memcache on
    valet memcache off
  displayName: 'PHP 7.1 memcached on and off'

# PHP 7.2 Command test cases

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet use 7.2
  displayName: 'Test switching to PHP 7.2'

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet xdebug on
    valet xdebug off
  displayName: 'PHP 7.2 xdebug on and off'

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet ioncube on
    valet ioncube off
  displayName: 'PHP 7.2 ioncube on and off'

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet memcache on
    valet memcache off
  displayName: 'PHP 7.2 memcached on and off'

# PHP 7.3 Command test cases

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet use 7.3
  displayName: 'Test switching to PHP 7.3'

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet xdebug on
    valet xdebug off
  displayName: 'PHP 7.3 xdebug on and off'

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet ioncube on
    valet ioncube off
  displayName: 'PHP 7.3 ioncube on and off'

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet memcache on
    valet memcache off
  displayName: 'PHP 7.3 memcached on and off'