trigger:
- release/azure-pipelines

pool:
  vmImage: 'macOS-10.14'

steps:

- script: |
    cd bin
    ln -s ../valet valet
    ls -la ~/
  displayName: 'Prepare binary folder'

#- script: |
#    brew tap henkrehorst/php
#    brew install valet-php@7.2
#  displayName: 'Install valet-php@7.2 dependency'
#
#- script: |
#    brew install composer
#    composer install
#  displayName: 'Move repo composer directory'
#
#- script: |
#    brew tap henkrehorst/php
#    brew install valet-php@7.2
#  displayName: 'Install valet-php@7.2 dependency'
#
#- script: |
#    valet fix
#    valet install
#  displayName: 'Install valet-plus'