trigger:
- release/azure-pipelines

pool:
  vmImage: 'macOS-10.14'

steps:

- script: |
    cd bin
    ln -s ../valet valet
    cd ..
  displayName: 'Prepare binary folder'

- script: |
    brew tap henkrehorst/php
    brew install valet-php@7.2
  displayName: 'Install valet-php@7.2 dependency'

- script: |
    brew install composer
    composer install
  displayName: 'Install composer'

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet fix
    valet install
  displayName: 'Install valet-plus'

- script: |
    export PATH="$PATH:`pwd`/bin"
    valet use 5.6
    valet use 7.0
    valet use 7.1
    valet use 7.3
  displayName: 'Test switching PHP versions'