trigger:
- release/azure-pipelines

pool:
  vmImage: 'macOS-10.14'

steps:

- script: |
    brew update
    brew tap henkrehorst/php
    brew install valet-php@7.2
  displayName: 'Install valet-php@7.2 dependency'

- script: |
    brew install composer
    composer global require neodork/valet-plus:dev-release/azure-pipelines
  displayName: 'Install composer and repository'

- script: |
    export PATH="$PATH:$HOME/.composer/vendor/bin"
    valet fix
    valet install
  displayName: 'Install valet-plus'